# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'
 
  variables:
  - variable group
steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Step 1: Back up the SQL database
      Invoke-Sqlcmd -ServerInstance "localdb\local" -Database "master" -Query "
      BACKUP DATABASE master
      TO DISK = 'C:\Users\AnushaSagarGadipelli\master.bak'
      WITH FORMAT, INIT;"
 
 - task: AzureCLI@2
  displayName: 'Upload Backup to Azure Blob Storage'
  inputs:
    azureSubscription: 'Free Trial(2240f72a-a86c-4097-b47e-f91902a1512c)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload --account-name '1ststorage1901'
                             --$(account-key)  
                             --container-name 'backupblod' 
                             --file "C:\Users\AnushaSagarGadipelli\master.bak" `
                             --name "master.bak"

