# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  

pool:
  vmImage: 'windows-latest'

variables:
  sqlServer: 'localdb\local'
  sqlDatabase: 'master'
  backupPath: 'path'
  storageAccount: '1ststorage1901'
  storageKey: 'key'
  containerName: 'backupblod'
  blobName: 'master.bak'

steps:
# Step 1: Back up the SQL database
- task: PowerShell@2
  displayName: "Backup SQL Database"
  inputs:
    targetType: 'inline'
    script: |
      Invoke-Sqlcmd -ServerInstance "$(sqlServer)" -Query "
      BACKUP DATABASE [$(sqlDatabase)]
      TO DISK = '$(backupPath)'
      WITH FORMAT, INIT;"

# Step 2: Upload the backup file to Azure Blob Storage
- task: AzureCLI@2
  displayName: "Upload to Azure Blob Storage"
  inputs:
    azureSubscription: 'Free Trial(2240f72a-a86c-4097-b47e-f91902a1512c)' 
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload \
        --account-name "$(storageAccount)" \
        --account-key "$(storageKey)" \
        --container-name "$(containerName)" \
        --file "$(backupPath)" \
        --name "$(blobName)"

