# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main  

pool:
  vmImage: 'windows-latest'

variables:
  group: 'new variable group'  

  sqlUsername: 'user'
  sqlPassword: 'sqlPassword'
  storageKey: 'key'
  backupPath: '$(System.DefaultWorkingDirectory)\master.bak'  # Backup file path
  blobName: 'master.bak'       
steps:
# Step 1: Back up the SQL database
- task: PowerShell@2
  displayName: "Backup SQL Database"
  inputs:
    targetType: 'inline'
    script: |
      $serverInstance = "sql-use-cca-qa-02.database.windows.net"
      $database = "db-adventurous"
      $username = "$(sqlUsername)"
      $password = "$(sqlPassword)"
      $securePassword = ConvertTo-SecureString $password -AsPlainText -Force

      Write-Host "Starting SQL Database Backup..."
      
      # Use username and password to authenticate with Azure SQL
      Invoke-Sqlcmd -ServerInstance $serverInstance -Database $database -Query "
        BACKUP DATABASE [$database]
        TO DISK = '$(System.DefaultWorkingDirectory)\master.bak'
        WITH FORMAT, INIT;" -Username $username -Password $password
      
      Write-Host "Backup Completed. File saved at $(System.DefaultWorkingDirectory)\master.bak."

# Step 2: Upload the backup file to Azure Blob Storage
- task: AzureCLI@2
  displayName: "Upload to Azure Blob Storage"
  inputs:
    azureSubscription: 'test_connection' 
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Uploading backup file to Azure Blob Storage..."
      az storage blob upload \
        --account-name "stusetest" \
        --account-key "$(storageKey)" \
        --container-name "test" \
        --file "$(System.DefaultWorkingDirectory)/master.bak" \
        --name "$(blobName)"
      echo "Upload Completed."
