# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  

pool:
  vmImage: 'windows-latest'

  
variables:
  group :new variable group
  storageKey: 'key'
    #blobName: 'master.bak'

steps:
# Step 1: Back up the SQL database
- task: PowerShell@2
  displayName: "Backup SQL Database"
  inputs:
    targetType: 'inline'
    script: |
      Invoke-Sqlcmd -ServerInstance sql-use-cca-qa-02.database.windows.net -Query "
      BACKUP DATABASE db-adventurous
      TO DISK = 'System.DefaultWorkingDirectory'
      WITH FORMAT, INIT;"

# Step 2: Upload the backup file to Azure Blob Storage
- task: AzureCLI@2
  displayName: "Upload to Azure Blob Storage"
  inputs:
    azureSubscription: 'test_connection' 
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload \
        --account-name "stusetest" \
        --account-key "$(key)" \
        --container-name "test" \
        --file "System.DefaultWorkingDirectory" \
#        --name "$(blobName)"

